const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const callbacks = new Map();
let image;
const canvas = {getContext: () => ({createImageData: () => ({data: new Uint8ClampedArray(4096)}), putImageData: value => {image = value;}})};
const buttons = Object.fromEntries(['btnStart','btnPause','btnStep','btnReset'].map(id => [id, {addEventListener: (name, fn) => callbacks.set(id, fn)}]));
const window = {addEventListener: () => {}, EmuUI: {getLeftADC: () => 0, getRightADC: () => 4095, setDisplayEnabled: () => {}}};
const context = {window, document: {getElementById: id => id === 'panel' ? canvas : buttons[id]}, Uint8Array, performance: {now: () => 0}, requestAnimationFrame: () => {}};
vm.runInNewContext(fs.readFileSync('emulator/web/emulator.js','utf8'), context);
const emu = window.Emu;
emu.onWasmReady({});
assert.equal(emu.getAdc(1), 555);
assert.equal(emu.getAdc(6), 105);
assert.equal(emu.getAdc(99), 0);
callbacks.get('btnPause')(); assert.equal(emu.isPaused(), true);
callbacks.get('btnStep')(); assert.equal(emu.consumeStep(), true); assert.equal(emu.consumeStep(), false);
callbacks.get('btnStep')(); callbacks.get('btnStart')(); assert.equal(emu.isPaused(), false); assert.equal(emu.consumeStep(), false);
const heap = new Uint8Array(3072); heap[0] = 1;
emu.renderFrame(0, 0, true, heap);
assert.equal(image.data[0], 255); assert.equal(image.data[1], 0); assert.equal(image.data[3], 255);
console.log('browser bridge checks passed');
